services:
  - type: web
    name: azul-plataforma
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: AZUL_SECRET_KEY
        generateValue: true
